version: '3.7'

services:
  bind_webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bind_webui
      - /etc/bind:/etc/bind
      - static_volume:/templates
    restart: always
    ports:
      - "5000:5000"
  
  
volumes:
  static_volume:
    external: true
  
